### ISSUE TITLE
After upgrading to 2.2.1: 'HTTPResponse' object has no attribute 'json'

### ISSUE THREAD

**Issue by p5B2EA84B3** [urllib3/urllib3#3383]
After upgrading to 2.2.1 response.json() throws error:

'HTTPResponse' object has no attribute 'json'

Downgrading to 2.2.0 fixed the problem.

**Comment by sethmlarson** [comment]
I'm not seeing that myself locally, also [inspecting the artifact on PyPI](https://inspector.pypi.io/project/urllib3/2.2.1/packages/a2/73/a68704750a7679d0b6d3ad7aa8d4da8e14e151ae82e6fee774e6e0d05ec8/urllib3-2.2.1-py3-none-any.whl/urllib3/response.py#line.365) shows the API is there. Closing this issue without a reproducer.

**Comment by vladimirtiukhtin** [comment]
I just bumped into the same. I had to switch to `.data`. How with a minor upgrade you could break that much?

**Comment by sethmlarson** [comment]
@vladimirtiukhtin Like was mentioned above, the API is there on PyPI: https://inspector.pypi.io/project/urllib3/2.5.0/packages/a7/c2/fe1e52489ae3122415c51f387e221dd0773709bad6c6cdaa599e8a2c5185/urllib3-2.5.0-py3-none-any.whl/urllib3/response.py#line.392

If the API truly was removed there'd be tons of issues being opened on our repository. So many people depend on that API at this point. I don't know how, but it's likely you're not using the version of urllib3 that you think you are, somehow?

**Comment by sigmavirus24** [comment]
Also, there's no need to be rude regardless of whatever baseless belief you have
